# Configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file

version: 2

updates:
    - package-ecosystem: "gradle"
      directory: "/"
      schedule:
        interval: "weekly"
      groups:
        kotlin-compose:
          patterns:
            - "org.jetbrains.kotlin.android*"
            - "androidx.compose.compiler*"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
