language: android
android:
  components:
    - build-tools-26.0.2
    - android-26

    # Additional components
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-26

script: ./gradlew check

# after_success:
#   - bash <(curl -s https://codecov.io/bash)
