name: 'Test Lib'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-caches-unit-test-v0-${{ hashFiles('build.gradle', 'settings.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}
          
      - name: Set up JDK 11 
        uses: actions/setup-java@v3 
        with: 
          distribution: 'adopt' 
          java-version: '11'

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          check_name: Unit Test Report
          report_paths: 'lib/build/test-results/testDebugUnitTest/TEST-*.xml'

  instrumentationTest:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-caches-instrumentation-test-v0-${{ hashFiles('build.gradle', 'settings.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}
          
      - name: Set up JDK 11 
        uses: actions/setup-java@v3 
        with: 
          distribution: 'adopt' 
          java-version: '11'

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          emulator-boot-timeout: 12000
          script: ./gradlew connectedAndroidTest

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          check_name: Instrumentation Test Report
          report_paths: 'lib/build/outputs/androidTest-results/connected/flavors/debugAndroidTest/TEST-*.xml'
